"""Create a starter ANSYS knowledge base with 7 essential documents.

Writes backend/knowledge_base/data/starter_knowledge.json with documents
covering element types, materials, convergence, meshing, APDL commands,
analysis types, and PyMAPDL usage.
"""

import json
import os
from pathlib import Path

OUTPUT_DIR = Path("backend/knowledge_base/data")
OUTPUT_FILE = OUTPUT_DIR / "starter_knowledge.json"

DOCUMENTS = [
    {
        "id": "ansys_element_types",
        "title": "Common ANSYS Element Types Reference",
        "content": (
            "# Common ANSYS Element Types Reference\n\n"
            "## SOLID185\n"
            "- **Nodes**: 8 nodes\n"
            "- **DOFs**: UX, UY, UZ\n"
            "- **Best Use**: General 3D structural analysis, plasticity, hyperelasticity\n"
            "- **Key KEYOPTs**: KEYOPT(2)=0 full integration, KEYOPT(2)=1 B-bar method\n\n"
            "## SOLID186\n"
            "- **Nodes**: 20 nodes (higher order)\n"
            "- **DOFs**: UX, UY, UZ\n"
            "- **Best Use**: Curved geometries, accurate stress gradients, contact problems\n"
            "- **Key KEYOPTs**: KEYOPT(2)=1 reduced integration (recommended)\n\n"
            "## SOLID187\n"
            "- **Nodes**: 10 nodes (tetrahedral)\n"
            "- **DOFs**: UX, UY, UZ\n"
            "- **Best Use**: Irregular geometries, automated meshing\n"
            "- **Key KEYOPTs**: KEYOPT(4) for extra displacement shapes\n\n"
            "## SHELL181\n"
            "- **Nodes**: 4 nodes\n"
            "- **DOFs**: UX, UY, UZ, ROTX, ROTY, ROTZ\n"
            "- **Best Use**: Thin to moderately thick shells, layered composites\n"
            "- **Key KEYOPTs**: KEYOPT(3)=2 for full integration\n\n"
            "## SHELL281\n"
            "- **Nodes**: 8 nodes (higher order)\n"
            "- **DOFs**: UX, UY, UZ, ROTX, ROTY, ROTZ\n"
            "- **Best Use**: Curved shells, high accuracy composites\n\n"
            "## BEAM188\n"
            "- **Nodes**: 2 nodes\n"
            "- **DOFs**: UX, UY, UZ, ROTX, ROTY, ROTZ\n"
            "- **Best Use**: Slender beams, Timoshenko beam theory\n"
            "- **Key KEYOPTs**: KEYOPT(3) for cross-section output\n\n"
            "## BEAM189\n"
            "- **Nodes**: 3 nodes (quadratic)\n"
            "- **DOFs**: UX, UY, UZ, ROTX, ROTY, ROTZ\n"
            "- **Best Use**: Beams with mid-side nodes, curved beams\n\n"
            "## SOLID70\n"
            "- **Nodes**: 8 nodes\n"
            "- **DOFs**: TEMP\n"
            "- **Best Use**: 3D steady-state or transient thermal analysis\n\n"
            "## SOLID90\n"
            "- **Nodes**: 20 nodes\n"
            "- **DOFs**: TEMP\n"
            "- **Best Use**: Higher order thermal analysis, curved boundaries\n\n"
            "## CONTA174\n"
            "- **Nodes**: 8 nodes\n"
            "- **Best Use**: 3D surface-to-surface contact (deformable)\n"
            "- **Key KEYOPTs**: KEYOPT(12) for contact behavior\n\n"
            "## TARGET170\n"
            "- **Nodes**: Variable\n"
            "- **Best Use**: 3D target surface paired with CONTA174\n\n"
            "## Element Selection Guidelines\n"
            "- Use SOLID186/187 for complex geometry with accuracy requirements\n"
            "- Use SOLID185 for large models where speed is important\n"
            "- Use SHELL181/281 for thin-walled structures (t/L < 0.1)\n"
            "- Use BEAM188/189 for slender structural members\n"
            "- Always match thermal elements (SOLID70/90) to structural topology\n"
        ),
    },
    {
        "id": "material_properties",
        "title": "Common Engineering Material Properties for ANSYS",
        "content": (
            "# Common Engineering Material Properties for ANSYS\n\n"
            "## Unit System Note\n"
            "ANSYS is unit-consistent. Always use one system throughout:\n"
            "- SI: Pa, N, m, kg, s\n"
            "- US Customary: psi, lbf, in, lbm\n\n"
            "## Steel A36\n"
            "```apdl\n"
            "MP,EX,1,200E9      ! Young's Modulus (Pa)\n"
            "MP,NUXY,1,0.3      ! Poisson's ratio\n"
            "MP,DENS,1,7850     ! Density (kg/m^3)\n"
            "MP,KXX,1,50        ! Thermal conductivity (W/m/K)\n"
            "MP,ALPX,1,12E-6    ! Thermal expansion coeff (1/K)\n"
            "TB,BISO,1,1        ! Bilinear isotropic hardening\n"
            "TBDATA,1,250E6,1E9 ! Yield stress, tangent modulus\n"
            "```\n\n"
            "## Aluminum 6061-T6\n"
            "```apdl\n"
            "MP,EX,2,68.9E9     ! Young's Modulus (Pa)\n"
            "MP,NUXY,2,0.33     ! Poisson's ratio\n"
            "MP,DENS,2,2700     ! Density (kg/m^3)\n"
            "MP,KXX,2,167       ! Thermal conductivity (W/m/K)\n"
            "MP,ALPX,2,23.6E-6  ! Thermal expansion coeff (1/K)\n"
            "TB,BISO,2,1\n"
            "TBDATA,1,276E6,0.7E9\n"
            "```\n\n"
            "## Copper (Pure)\n"
            "```apdl\n"
            "MP,EX,3,117E9\n"
            "MP,NUXY,3,0.34\n"
            "MP,DENS,3,8960\n"
            "MP,KXX,3,401\n"
            "MP,ALPX,3,17E-6\n"
            "```\n\n"
            "## Titanium Ti-6Al-4V\n"
            "```apdl\n"
            "MP,EX,4,113.8E9\n"
            "MP,NUXY,4,0.342\n"
            "MP,DENS,4,4430\n"
            "MP,KXX,4,6.7\n"
            "MP,ALPX,4,8.6E-6\n"
            "TB,BISO,4,1\n"
            "TBDATA,1,880E6,1.1E9\n"
            "```\n\n"
            "## Temperature-Dependent Properties\n"
            "Use MPTEMP and MPDATA for temperature-dependent values:\n"
            "```apdl\n"
            "MPTEMP,1,0,100,200,300    ! Temperature points (C)\n"
            "MPDATA,EX,1,1,200E9,195E9,190E9,185E9\n"
            "```\n"
        ),
    },
    {
        "id": "convergence_troubleshooting",
        "title": "ANSYS Convergence Troubleshooting Guide",
        "content": (
            "# ANSYS Convergence Troubleshooting Guide\n\n"
            "## Substep Size Issues\n"
            "- Reduce initial substep size: NSUBST,20,1000,10\n"
            "- Enable bisection: AUTOTS,ON\n"
            "- Check for abrupt load changes\n\n"
            "## Element Distortion\n"
            "- Improve mesh quality (Jacobian ratio < 30)\n"
            "- Use SOLID186 instead of SOLID185 in distorted regions\n"
            "- Enable large deformation with NLGEOM,ON if needed\n"
            "- Check for negative Jacobian with /ESHAPE,1 visualization\n\n"
            "## Contact Issues\n"
            "- Check contact detection: KEYOPT(12) settings\n"
            "- Adjust normal stiffness: KEYOPT(10), FKN factor\n"
            "- Use CNCHECK command to verify contact pairs\n"
            "- Try Augmented Lagrangian: KEYOPT(2)=0\n"
            "- Reduce penetration tolerance: FTOLN value\n"
            "- Enable contact stabilization for rigid body motion\n\n"
            "## Material Model Issues\n"
            "- Ensure material constants are physically valid\n"
            "- Check plasticity: yield stress must be > 0\n"
            "- For hyperelastic, verify Drucker stability\n"
            "- Use TBPLOT to visualize material curves\n\n"
            "## Boundary Condition Problems\n"
            "- Verify sufficient constraints (no rigid body motion)\n"
            "- Check for overconstrained nodes\n"
            "- Ramp loads gradually: KBC,0\n"
            "- Use weak springs if needed: STABILIZE command\n\n"
            "## Large Deformation Settings\n"
            "```apdl\n"
            "NLGEOM,ON          ! Enable large deformation\n"
            "NROPT,FULL,,ON     ! Full Newton-Raphson with adaptive descent\n"
            "ARCLEN,ON          ! Arc-length method for buckling\n"
            "```\n\n"
            "## Recommended Solver Settings for Convergence\n"
            "```apdl\n"
            "AUTOTS,ON\n"
            "NSUBST,10,1000,5\n"
            "CNVTOL,F,,0.005    ! Force convergence tolerance 0.5%\n"
            "CNVTOL,U,,0.05     ! Displacement convergence tolerance 5%\n"
            "NCNV,2             ! Continue after convergence failure\n"
            "NEQIT,50           ! Maximum equilibrium iterations\n"
            "LNSRCH,ON          ! Line search\n"
            "PRED,ON            ! Predictor step\n"
            "```\n\n"
            "## Debugging Steps\n"
            "1. Review Newton-Raphson residuals plot (/POST1 + PLNSOL,NRES)\n"
            "2. Check element status for material yielding\n"
            "3. Review contact status (CNCHECK,DETAIL)\n"
            "4. Reduce load and verify linear response first\n"
            "5. Run with DEBUG output: OUTRES,ALL,ALL\n"
        ),
    },
    {
        "id": "mesh_best_practices",
        "title": "ANSYS Mesh Best Practices",
        "content": (
            "# ANSYS Mesh Best Practices\n\n"
            "## General Guidelines\n"
            "- Target aspect ratio < 5 for structural, < 3 for thermal\n"
            "- Jacobian ratio < 30 (ideally < 10)\n"
            "- Warping factor < 0.4 for shells\n"
            "- Parallel deviation < 70 degrees\n"
            "- Maximum corner angle < 165 degrees\n\n"
            "## Mesh Convergence Study Procedure\n"
            "1. Start with a coarse mesh and solve\n"
            "2. Record key result (max stress, displacement)\n"
            "3. Refine mesh by factor of 2 globally or locally\n"
            "4. Re-solve and compare results\n"
            "5. Repeat until change < 5% between refinements\n"
            "6. Use Richardson extrapolation for accuracy estimate\n\n"
            "## Structural Meshing\n"
            "- Use hex elements (SOLID185/186) where possible\n"
            "- Refine near stress concentrations (holes, fillets, notches)\n"
            "- At least 3 elements through thickness for bending\n"
            "- Use SOLID187 (tet) only when hex meshing is impractical\n"
            "- Apply mesh sizing controls at critical regions\n\n"
            "## CFD Meshing with y+ Guidance\n"
            "- For wall-bounded flows:\n"
            "  - y+ ~ 1 for low-Reynolds (resolving viscous sublayer)\n"
            "  - y+ ~ 30-300 for high-Reynolds (wall functions)\n"
            "- First cell height: y = y+ * nu / u_tau\n"
            "  where u_tau = sqrt(tau_w / rho)\n"
            "- Growth rate 1.2-1.3 from wall\n\n"
            "## Common APDL Meshing Commands\n"
            "```apdl\n"
            "! Element type and size\n"
            "ET,1,SOLID186\n"
            "ESIZE,0.01         ! Global element size (m)\n"
            "LESIZE,ALL,,,10    ! 10 elements on all lines\n"
            "\n"
            "! Mesh controls\n"
            "MSHKEY,1           ! Mapped meshing\n"
            "MSHKEY,0           ! Free meshing (default)\n"
            "MSHAPE,1,3D        ! Tetrahedral (3D)\n"
            "MSHAPE,0,3D        ! Hexahedral (3D)\n"
            "\n"
            "! Mesh refinement\n"
            "VMESH,ALL          ! Mesh all volumes\n"
            "AREFINE,ALL,,,1    ! Refine surface mesh by level 1\n"
            "NREFINE,ALL,,,1    ! Refine around nodes\n"
            "\n"
            "! Mesh quality check\n"
            "CHECK,ESEL         ! Check element quality\n"
            "MCHECK,0           ! Verify mesh connectivity\n"
            "```\n"
        ),
    },
    {
        "id": "apdl_commands_reference",
        "title": "Most Used APDL Commands Reference",
        "content": (
            "# Most Used APDL Commands Reference\n\n"
            "## Geometry Creation\n"
            "```apdl\n"
            "K,1,0,0,0          ! Keypoint at (0,0,0)\n"
            "L,1,2              ! Line between keypoints 1 and 2\n"
            "A,1,2,3,4          ! Area from keypoints\n"
            "V,1,2,3,4,5,6,7,8  ! Volume from keypoints\n"
            "BLOCK,0,1,0,1,0,1  ! Block volume\n"
            "CYL4,0,0,0.5       ! Cylinder\n"
            "SPHERE,0,1         ! Sphere\n"
            "```\n\n"
            "## Boolean Operations\n"
            "```apdl\n"
            "VADD,ALL           ! Add (union) all volumes\n"
            "VSUB,1,2           ! Subtract volume 2 from 1\n"
            "VOVLAP,ALL         ! Overlap volumes\n"
            "VGLUE,ALL          ! Glue volumes (shared boundaries)\n"
            "AGLUE,ALL          ! Glue areas\n"
            "```\n\n"
            "## Element Types and Material\n"
            "```apdl\n"
            "ET,1,SOLID186      ! Define element type 1\n"
            "ET,2,CONTA174      ! Define contact element\n"
            "KEYOPT,1,2,1       ! Set element key option\n"
            "MP,EX,1,200E9      ! Material property\n"
            "TB,BISO,1,1        ! Bilinear isotropic plasticity\n"
            "TBDATA,1,250E6,1E9 ! Table data\n"
            "```\n\n"
            "## Meshing\n"
            "```apdl\n"
            "ESIZE,0.01\n"
            "VMESH,ALL\n"
            "AMESH,ALL\n"
            "LMESH,ALL\n"
            "SMESH             ! Sweep mesh\n"
            "VSWEEP,ALL\n"
            "```\n\n"
            "## Analysis Types\n"
            "```apdl\n"
            "ANTYPE,STATIC     ! Static analysis\n"
            "ANTYPE,MODAL      ! Modal analysis\n"
            "ANTYPE,HARMIC     ! Harmonic analysis\n"
            "ANTYPE,TRANS      ! Transient analysis\n"
            "ANTYPE,BUCKLE     ! Buckling analysis\n"
            "```\n\n"
            "## Boundary Conditions\n"
            "```apdl\n"
            "D,ALL,ALL,0        ! Fix all DOFs on selected nodes\n"
            "D,NODE,UX,0        ! Fix X displacement\n"
            "D,NODE,ALL,0       ! Fix all DOFs\n"
            "DSYM,SYMM,X,0      ! Symmetry BC on X plane\n"
            "```\n\n"
            "## Loads\n"
            "```apdl\n"
            "F,NODE,FX,1000     ! Force at node\n"
            "SF,ALL,PRES,1E6    ! Pressure on selected elements\n"
            "BF,ALL,TEMP,100    ! Body temperature load\n"
            "ACEL,0,0,9.81      ! Acceleration (gravity)\n"
            "OMEGA,0,0,100      ! Angular velocity (rad/s)\n"
            "```\n\n"
            "## Selection Commands\n"
            "```apdl\n"
            "ALLSEL,ALL         ! Select everything\n"
            "NSEL,S,LOC,X,0     ! Select nodes at X=0\n"
            "ESEL,S,TYPE,,1     ! Select elements of type 1\n"
            "ASEL,S,LOC,Z,0     ! Select areas at Z=0\n"
            "NSEL,A,LOC,X,1     ! Add nodes at X=1 to selection\n"
            "NSEL,R,LOC,Y,0,1   ! Reselect within Y range\n"
            "```\n\n"
            "## Solving\n"
            "```apdl\n"
            "/SOLU\n"
            "SOLVE\n"
            "FINISH\n"
            "```\n\n"
            "## Postprocessing\n"
            "```apdl\n"
            "/POST1\n"
            "SET,LAST           ! Read last result set\n"
            "PLNSOL,S,EQV       ! Plot von Mises stress\n"
            "PLNSOL,U,SUM       ! Plot total displacement\n"
            "PRNSOL,S,COMP      ! Print stress components\n"
            "NSORT,S,EQV        ! Sort nodes by von Mises stress\n"
            "PRNSOL,S,EQV       ! Print sorted stresses\n"
            "```\n"
        ),
    },
    {
        "id": "analysis_setup_guides",
        "title": "ANSYS Analysis Type Setup Guides",
        "content": (
            "# ANSYS Analysis Type Setup Guides\n\n"
            "## Static Structural Analysis\n"
            "```apdl\n"
            "/PREP7\n"
            "ET,1,SOLID186\n"
            "MP,EX,1,200E9\n"
            "MP,NUXY,1,0.3\n"
            "! ... geometry and mesh ...\n"
            "/SOLU\n"
            "ANTYPE,STATIC\n"
            "NLGEOM,OFF         ! Linear (ON for nonlinear)\n"
            "NSUBST,1\n"
            "! ... BCs and loads ...\n"
            "SOLVE\n"
            "FINISH\n"
            "/POST1\n"
            "SET,LAST\n"
            "PLNSOL,S,EQV\n"
            "FINISH\n"
            "```\n\n"
            "## Modal Analysis\n"
            "```apdl\n"
            "/SOLU\n"
            "ANTYPE,MODAL\n"
            "MODOPT,LANB,10     ! Block Lanczos, extract 10 modes\n"
            "MXPAND,10,,,YES    ! Expand all modes with stress\n"
            "EQSLV,SPARSE       ! Sparse direct solver\n"
            "! Apply constraints (no loads in modal)\n"
            "SOLVE\n"
            "FINISH\n"
            "/POST1\n"
            "SET,LIST           ! List natural frequencies\n"
            "SET,1,1            ! Read mode 1\n"
            "PLNSOL,U,SUM       ! Plot mode shape\n"
            "FINISH\n"
            "```\n\n"
            "## Thermal Steady-State Analysis\n"
            "```apdl\n"
            "/PREP7\n"
            "ET,1,SOLID90\n"
            "MP,KXX,1,50        ! Thermal conductivity (W/m/K)\n"
            "MP,DENS,1,7850\n"
            "MP,C,1,500         ! Specific heat (J/kg/K)\n"
            "! ... geometry and mesh ...\n"
            "/SOLU\n"
            "ANTYPE,STATIC      ! Steady-state thermal = STATIC\n"
            "D,ALL,TEMP,20      ! Temperature BC (Dirichlet)\n"
            "SF,LOAD_AREA,CONV,100,25  ! Convection: h=100, T_bulk=25\n"
            "BF,ALL,HGEN,1E6   ! Heat generation (W/m^3)\n"
            "SOLVE\n"
            "FINISH\n"
            "/POST1\n"
            "SET,LAST\n"
            "PLNSOL,TEMP        ! Plot temperature distribution\n"
            "FINISH\n"
            "```\n\n"
            "## Thermal-Structural Coupled Analysis\n"
            "```apdl\n"
            "! Step 1: Thermal analysis\n"
            "ET,1,SOLID90\n"
            "! ... thermal solve ...\n"
            "! Step 2: Structural analysis with thermal loads\n"
            "ET,1,SOLID186\n"
            "MP,ALPX,1,12E-6    ! Thermal expansion coeff\n"
            "TREF,20            ! Reference temperature\n"
            "LDREAD,TEMP,,,,,'thermal_results','rst'  ! Read thermal results\n"
            "ANTYPE,STATIC\n"
            "SOLVE\n"
            "```\n\n"
            "## Buckling Analysis\n"
            "```apdl\n"
            "! Prerequisite: Run static analysis first\n"
            "/SOLU\n"
            "ANTYPE,BUCKLE\n"
            "BUCOPT,LANB,5      ! Extract 5 buckling modes\n"
            "SOLVE\n"
            "FINISH\n"
            "/POST1\n"
            "SET,LIST           ! List buckling load factors\n"
            "SET,1,1\n"
            "PLNSOL,U,SUM\n"
            "FINISH\n"
            "```\n\n"
            "## Harmonic Analysis\n"
            "```apdl\n"
            "/SOLU\n"
            "ANTYPE,HARMIC\n"
            "HROPT,FULL         ! Full method\n"
            "HROUT,ON           ! Output in real/imaginary\n"
            "HARFRQ,0,1000      ! Frequency range 0-1000 Hz\n"
            "NSUBST,100         ! 100 frequency steps\n"
            "DMPRAT,0.02        ! 2% damping ratio\n"
            "! ... loads ...\n"
            "SOLVE\n"
            "FINISH\n"
            "/POST26\n"
            "NSOL,2,NODE,U,Y    ! Store Y displacement of node\n"
            "PLVAR,2            ! Plot frequency response\n"
            "FINISH\n"
            "```\n"
        ),
    },
    {
        "id": "pymapdl_quick_start",
        "title": "PyMAPDL Quick Start Guide",
        "content": (
            "# PyMAPDL Quick Start Guide\n\n"
            "## Installation\n"
            "```bash\n"
            "pip install ansys-mapdl-core\n"
            "pip install ansys-mapdl-reader  # for result files\n"
            "```\n\n"
            "## Basic Usage Example\n"
            "```python\n"
            "from ansys.mapdl.core import launch_mapdl\n"
            "\n"
            "# Launch MAPDL\n"
            "mapdl = launch_mapdl()\n"
            "print(mapdl)\n"
            "\n"
            "# Preprocessor\n"
            "mapdl.prep7()\n"
            "\n"
            "# Define element type\n"
            "mapdl.et(1, 'SOLID186')\n"
            "\n"
            "# Material properties\n"
            "mapdl.mp('EX', 1, 200e9)\n"
            "mapdl.mp('NUXY', 1, 0.3)\n"
            "mapdl.mp('DENS', 1, 7850)\n"
            "\n"
            "# Create geometry\n"
            "mapdl.block(0, 1, 0, 0.1, 0, 0.1)\n"
            "\n"
            "# Mesh\n"
            "mapdl.esize(0.02)\n"
            "mapdl.vmesh('ALL')\n"
            "\n"
            "# Solution\n"
            "mapdl.slashsolu()\n"
            "mapdl.antype('STATIC')\n"
            "\n"
            "# Boundary conditions\n"
            "mapdl.nsel('S', 'LOC', 'X', 0)\n"
            "mapdl.d('ALL', 'ALL', 0)\n"
            "mapdl.allsel()\n"
            "\n"
            "# Apply load\n"
            "mapdl.nsel('S', 'LOC', 'X', 1)\n"
            "mapdl.f('ALL', 'FX', 1000)\n"
            "mapdl.allsel()\n"
            "\n"
            "# Solve\n"
            "mapdl.solve()\n"
            "mapdl.finish()\n"
            "\n"
            "# Post-processing\n"
            "mapdl.post1()\n"
            "mapdl.set('LAST')\n"
            "mapdl.post_processing.plot_nodal_eqv_stress()\n"
            "\n"
            "# Get result arrays\n"
            "stress = mapdl.post_processing.nodal_eqv_stress()\n"
            "disp = mapdl.post_processing.nodal_displacement('NORM')\n"
            "print(f'Max stress: {stress.max():.3e} Pa')\n"
            "print(f'Max displacement: {disp.max():.6f} m')\n"
            "\n"
            "mapdl.exit()\n"
            "```\n\n"
            "## Key Methods\n"
            "- `mapdl.run(cmd)` - run any APDL command as string\n"
            "- `mapdl.parameters` - access ANSYS parameters as dict-like object\n"
            "- `mapdl.geometry` - access geometry information\n"
            "- `mapdl.mesh` - access mesh information (nodes, elements)\n"
            "- `mapdl.solution` - access solution settings\n"
            "- `mapdl.post_processing` - rich postprocessing object\n"
            "- `mapdl.result` - read result file directly\n\n"
            "## Result Extraction\n"
            "```python\n"
            "# Modal analysis results\n"
            "mapdl.post1()\n"
            "result = mapdl.result\n"
            "# Get natural frequencies\n"
            "freq = result.time_values\n"
            "print('Natural frequencies (Hz):', freq)\n"
            "\n"
            "# Nodal displacement for mode 1\n"
            "nnum, disp = result.nodal_displacement(0)\n"
            "\n"
            "# Nodal stress for mode 1\n"
            "nnum, stress = result.nodal_stress(0)\n"
            "```\n\n"
            "## Useful Tips\n"
            "- Use `mapdl.queries` for complex selections\n"
            "- `mapdl.input(filename)` to run existing APDL scripts\n"
            "- `mapdl.download_result(path)` to fetch result files\n"
            "- Connect to existing MAPDL: `launch_mapdl(port=50052)`\n"
            "- Use `mapdl.clear()` to reset the MAPDL database\n"
        ),
    },
]


def main() -> None:
    """Create the starter knowledge base JSON file."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as fh:
        json.dump(DOCUMENTS, fh, ensure_ascii=False, indent=2)

    print(f"Created {OUTPUT_FILE} with {len(DOCUMENTS)} documents:")
    for doc in DOCUMENTS:
        content_len = len(doc["content"])
        print(f"  [{doc['id']}] {doc['title']} ({content_len} chars)")

    print("\nDone. Run scripts/build_starter_vectordb.py next.")


if __name__ == "__main__":
    main()
